spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service
              uri: http://patient-service:8081
              predicates:
                - Path=/patient/**